### PR TITLE
Fix library properties version: 1.2.0

### PR DESCRIPTION
**Pull request by marqdevx**
* Change version number inside library.properties

### CODE REVIEW

**Comment by marqdevx** [comment]
@alranel @Rocketct 
Could you please merge it, so we can make accessible the last release inside the library manager?
Thanks!

**Comment by per1234** [comment]
> so we can make accessible the last release inside the library manager?

@marqdevx that goal will not be accomplished by changing the `version` value.

Library Manager works from tags, and making the library compliant after the fact doesn't change the fact that it was non-compliant at the time of the `v1.2.0` release. The only way to distribute the latest version of the library is to make a new tag, being sure that it is made compliant this time. So it would actually make more sense to change the version to `1.2.1`, then push a `1.2.1` tag. That will result in the latest library code being available for installation via Library Manager.

**Comment by marqdevx** [comment]
oh I thought we could remove the release and make a new one.
I'll commit then with the version 1.2.1
thanks

**Comment by per1234** [comment]
>I thought we could remove the release and make a new one.

You're right. It is currently allowed to modify releases:
https://github.com/arduino/library-registry/blob/main/FAQ.md#i-did-something-wrong-how-can-i-change-or-unpublish-an-already-published-library

However, it's not really best practices to modify tags and we're planning to change the policy to prohibit it.

**Pull request merged**
